version: '3.8'
services:

  db:
    container_name: mysql
    image: "mysql:5.7"
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=project_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
     
 
  frontend:
    container_name: angular_container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 4207:80
    
    depends_on:
      - db
  backend:
    container_name: spring_container
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8087:8080
    depends_on:
      - db
  

