version: '3.8'
services:

  db:
    platform: linux/x86_64
    image: "mysql:5.7"
    ports:
      - 3306:3306
    #volumes:
      #- C:\Users\hp\Documents\projet-rachid\backend\src\main\resources\db=/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=project_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    networks:
      - my_network

  backend:
    depends_on:
      - db
    
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: my_backend_image:latest
    restart: always
    ports:
      - 8087:8080
    networks:
      - my_network

  frontend:
    depends_on:
      - db
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: my_frontend_image:latest
    ports:
      - 4207:80
    networks:
      - my_network

networks:
  my_network:
    
#volumes:
  #db_data=C:\Users\hp\Documents\projet-rachid\backend\src\main\resources\db
