version: '3.8'
services:
  
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: "jG5*p#XtW9b@E3"
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - my_network
  
  backend: 
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: back-test:latest
    restart: always
    ports:
      - 8087:8080
    links:
      - db
    networks:
      - my_network


  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: front-test:latest
    ports:
      - 4207:80
    links:
      - backend
    networks:
      - my_network

networks:
  my_network:
volumes:
  data:
