version: '2'
services:

  db:
    platform: linux/x86_64
    image: "mysql:5.7"
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=project_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      networks:
         - mynetwork

  backend:
    depends_on:
      - db
    build: ./backend
    restart: always
    ports:
      - 8087:8080
      networks:
        - mynetwork

  frontend:
    depends_on:
      - db
    build: ./frontend
    ports:
      - 4207:80
      networks:
        - mynetwork
        
networks:
  mynetwork:
    drive: bridge

