version: '3.8'
services:
  
  postgres_db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
        POSTGRES_DB: "mydb"
        POSTGRES_USER: "hdinfo"
        POSTGRES_PASSWORD: "jG5*p#XtW9b@E3"
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - my_network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8085:80"
    environment:
      PMA_ARBITRARY: 1
    networks:
      - my_network 
  backend: 
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: back-test:latest
    container_name: back-cont 
    restart: always
    ports:
      - 8087:8080
    environment:
          DB_SERVER: "postgres_db"
          POSTGRES_DB: "mydb"
          POSTGRES_USER: "hdinfo"
          POSTGRES_PASSWORD: "jG5*p#XtW9b@E3"
    links:
      - postgres_db
    networks:
      - my_network


  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: front-test:latest
    container_name: front-cont
    ports:
      - 4207:80
    links:
      - backend
    networks:
      - my_network

networks:
  my_network:
volumes:
  data:
  
