version: '3.8'
services:

  db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: "jG5*p#XtW9b@E3"
    ports:
      - "5433:5432"
    volumes:
      - /data:/var/lib/postgresql/data
    networks:
      - docker-spring-angular
     
 
  frontend:
    container_name: angular_container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 4207:80
    networks:
      - docker-spring-angular
    
    depends_on:
      - db
  backend:
    container_name: spring_container
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8087:8080
    depends_on:
      - db
    networks:
      - docker-spring-angular
networks:
  docker-spring-angular:
  

