version: '3.8'
services:

  db:
    platform: linux/x86_64
    image: "mysql:5.7"
    ports:
      - 3306:3306
    #volumes:
      #- C:\Users\hp\Documents\projet-rachid\backend\src\main\resources\db=/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=project_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  backend:
    depends_on:
      - db
    build: ./backend
    restart: always
    ports:
      - 8080:8080

  frontend:
    depends_on:
      - db
    build: ./frontend
    ports:
      - 4200:80
    
#volumes:
  #db_data=C:\Users\hp\Documents\projet-rachid\backend\src\main\resources\db