version: '3.8'
services:

  
  backend:
    
    
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: back-test:latest
    restart: always
    ports:
      - 8087:8080
    networks:
      - my_network

  frontend:
   
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: front-test:latest
    ports:
      - 4207:80
    networks:
      - my_network

networks:
  my_network:
    
#volumes:
  #db_data=C:\Users\hp\Documents\projet-rachid\backend\src\main\resources\db
