version: '3.8'
services:
  
    db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: project_db
      MYSQL_PASSWORD: password
    networks:
      - my_network
  
  backend: 
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: back-test:latest
    restart: always
    ports:
      - 8087:8080
    depends_on:
      - db
    links:
      - db
    networks:
      - my_network


  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: front-test:latest
    ports:
      - 4207:80
    links:
      - backend
    networks:
      - my_network

networks:
  my_network:
