version: '3.8'
services:

  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: "jG5*p#XtW9b@E3"
    ports:
      - "5433:5432"
    volumes:
      - /data:/var/lib/postgresql/data
    networks:
      - my_network

  backend:
    depends_on:
      - db
    
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: my_backend_image:latest
    restart: always
    ports:
      - 8087:8080
    networks:
      - my_network

  frontend:
    depends_on:
      - db
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: my_frontend_image:latest
    ports:
      - 4207:80
    networks:
      - my_network

networks:
  my_network:
    
#volumes:
  #db_data=C:\Users\hp\Documents\projet-rachid\backend\src\main\resources\db
